version: "3.9"
services:
  db:
    image: postgres:12.3-alpine
    restart: always
    environment:
      # username: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - "db"

